spring:
  application:
    name: Lata-Velha

  datasource:
    url: jdbc:postgresql://postgres:5432/lata_velha
    username: admin
    password: admin123

logging:
  level:
    br.com.lata.velha.shared.infrastructure.observability: DEBUG
    io.opentelemetry: DEBUG
