spring:
  application:
    name: Lata-Velha

  datasource:
    url: jdbc:postgresql://localhost:5432/lata_velha
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/migration-postgresql

  mail:
    host: smtp.gmail.com
    port: 587
    username: lata.velha.fiap@gmail.com
    password: suxj nonb utdn dokg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
    jwt:
  issuer: lata-velha
  expires-in: 3600

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8
