apiVersion: v1
kind: ConfigMap
metadata:
  name: lata-velha-config
  namespace: lata-velha
data:
  ENVIRONMENT: "prod"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  JWT_ISSUER: "lata-velha"
  JWT_EXPIRES_IN: "3600"
  OTEL_SERVICE_NAME: "lata-velha"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp.us5.datadoghq.com"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "https://otlp.us5.datadoghq.com/v1/traces"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "https://otlp.us5.datadoghq.com/v1/metrics"
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "https://otlp.us5.datadoghq.com/v1/logs"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "delta"
