apiVersion: v1
kind: ConfigMap
metadata:
  name: lata-velha-config
  namespace: lata-velha
data:
  ENVIRONMENT: "prod"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  JWT_ISSUER: "lata-velha"
  JWT_EXPIRES_IN: "3600"
