version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-lata-velha
    environment:
      POSTGRES_DB: lata_velha
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
