-- =============================================================================
-- V10: Refactor auth schema — separate User entity from Funcionario
--
-- Changes:
--   ROLE        : ID type SERIAL (INTEGER) → UUID
--   FUNCIONARIO : removed USER_NAME / PASSWORD / ATIVO; added USER_ID (UUID)
--   USERS       : new table for authentication credentials
--   USER_ROLES  : new join table (User ↔ Role)
--   CARGO_ROLE  : recreated with ROLE_ID UUID to match new ROLE.ID type
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Drop tables that depend on ROLE or carry the old FUNCIONARIO structure
--    (respecting FK order)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS CARGO_ROLE;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS ROLE;

-- ---------------------------------------------------------------------------
-- 2. ROLE — UUID primary key (generated by gen_random_uuid())
-- ---------------------------------------------------------------------------
CREATE TABLE ROLE (
    ID   UUID        NOT NULL,
    NOME VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);

-- ---------------------------------------------------------------------------
-- 3. USERS — new authentication entity
-- ---------------------------------------------------------------------------
CREATE TABLE USERS (
    ID                UUID         NOT NULL,
    USER_NAME         VARCHAR(255) NOT NULL,
    EMAIL             VARCHAR(255) NOT NULL,
    CREDENTIAL        VARCHAR(255) NOT NULL,
    ATIVO             BOOLEAN      NOT NULL,
    CRIACAO_DATE      TIMESTAMP    NOT NULL,
    ULTIMO_LOGIN_DATE TIMESTAMP,
    CONSTRAINT PK_USERS       PRIMARY KEY (ID),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL)
);

-- ---------------------------------------------------------------------------
-- 4. USER_ROLES — join table (User ↔ Role)
-- ---------------------------------------------------------------------------
CREATE TABLE USER_ROLES (
    USER_ID UUID NOT NULL,
    ROLE_ID UUID NOT NULL,
    CONSTRAINT PK_USER_ROLES      PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

-- ---------------------------------------------------------------------------
-- 5. CARGO_ROLE — recreated with ROLE_ID UUID to match new ROLE.ID type
-- ---------------------------------------------------------------------------
CREATE TABLE CARGO_ROLE (
    CARGO_ID BIGINT NOT NULL,
    ROLE_ID  UUID   NOT NULL,
    CONSTRAINT PK_CARGO_ROLE       PRIMARY KEY (CARGO_ID, ROLE_ID),
    CONSTRAINT FK_CARGO_ROLE_CARGO FOREIGN KEY (CARGO_ID) REFERENCES CARGO(ID),
    CONSTRAINT FK_CARGO_ROLE_ROLE  FOREIGN KEY (ROLE_ID)  REFERENCES ROLE(ID)
);

-- ---------------------------------------------------------------------------
-- 6. FUNCIONARIO — no more USER_NAME / PASSWORD / ATIVO; has USER_ID instead
-- ---------------------------------------------------------------------------
CREATE TABLE FUNCIONARIO (
    ID       BIGSERIAL    PRIMARY KEY,
    NOME     VARCHAR(100) NOT NULL,
    CARGO_ID BIGINT       NOT NULL,
    USER_ID  UUID         NOT NULL,
    CONSTRAINT FK_FUNCIONARIO_CARGO FOREIGN KEY (CARGO_ID) REFERENCES CARGO(ID),
    CONSTRAINT FK_FUNCIONARIO_USER  FOREIGN KEY (USER_ID)  REFERENCES USERS(ID)
);

-- =============================================================================
-- Seed data
-- =============================================================================

-- ROLE — IDs generated by the database
INSERT INTO ROLE (ID, NOME) VALUES
    (gen_random_uuid(), 'ADMIN'),
    (gen_random_uuid(), 'USER'),
    (gen_random_uuid(), 'MECANICO');

-- CARGO_ROLE — ROLE IDs looked up by name; CARGO IDs from V2 (ADMIN=1, ATENDENTE=2, MECANICO=3)
INSERT INTO CARGO_ROLE (CARGO_ID, ROLE_ID)
SELECT 1, ID FROM ROLE WHERE NOME = 'ADMIN'    UNION ALL
SELECT 1, ID FROM ROLE WHERE NOME = 'USER'     UNION ALL
SELECT 1, ID FROM ROLE WHERE NOME = 'MECANICO' UNION ALL
SELECT 2, ID FROM ROLE WHERE NOME = 'USER'     UNION ALL
SELECT 3, ID FROM ROLE WHERE NOME = 'MECANICO';

-- USERS — passwords meet Senha rules (8+ chars, ≥1 digit, ≥1 special char)
--   admin@latavelha.com    → Admin@123
--   atendente@latavelha.com → Atend@123
--   mecanico@latavelha.com  → Mecan@123
INSERT INTO USERS (ID, USER_NAME, EMAIL, CREDENTIAL, ATIVO, CRIACAO_DATE) VALUES
    (gen_random_uuid(),
     'admin@latavelha.com', 'admin@latavelha.com',
     '$2a$10$1dSgICxSKMCZaDflzpaD.Ovyb34nyvz/NfvPsg70gBfNcZ9o4u3UW',
     TRUE, NOW()),
    (gen_random_uuid(),
     'atendente@latavelha.com', 'atendente@latavelha.com',
     '$2a$10$TCdxfIklS2vW.M5mt1n.FutYI6aK5rE/vpDhNm7VpfS51O2KkpiLq',
     TRUE, NOW()),
    (gen_random_uuid(),
     'mecanico@latavelha.com', 'mecanico@latavelha.com',
     '$2a$10$/zxmjorM9.FdmAr6GZ/lcOJNwBodq5XGjtTwx9B7c4lkcYj.2DqDi',
     TRUE, NOW());

-- USER_ROLES — both sides looked up by name / email
INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
SELECT U.ID, R.ID FROM USERS U, ROLE R
WHERE U.EMAIL = 'admin@latavelha.com'     AND R.NOME = 'ADMIN'    UNION ALL
SELECT U.ID, R.ID FROM USERS U, ROLE R
WHERE U.EMAIL = 'admin@latavelha.com'     AND R.NOME = 'USER'     UNION ALL
SELECT U.ID, R.ID FROM USERS U, ROLE R
WHERE U.EMAIL = 'admin@latavelha.com'     AND R.NOME = 'MECANICO' UNION ALL
SELECT U.ID, R.ID FROM USERS U, ROLE R
WHERE U.EMAIL = 'atendente@latavelha.com' AND R.NOME = 'USER'     UNION ALL
SELECT U.ID, R.ID FROM USERS U, ROLE R
WHERE U.EMAIL = 'mecanico@latavelha.com'  AND R.NOME = 'MECANICO';

-- FUNCIONARIO — USER_ID looked up by email
INSERT INTO FUNCIONARIO (NOME, CARGO_ID, USER_ID)
SELECT 'Fiap',  1, ID FROM USERS WHERE EMAIL = 'admin@latavelha.com'     UNION ALL
SELECT 'Maria', 2, ID FROM USERS WHERE EMAIL = 'atendente@latavelha.com' UNION ALL
SELECT 'Jose',  3, ID FROM USERS WHERE EMAIL = 'mecanico@latavelha.com';
