ALTER TABLE PECA_ALOCADA
    ADD COLUMN VALOR_UNITARIO NUMERIC(10,2) NOT NULL DEFAULT 0,
    ADD COLUMN QTD_INSTALADA INTEGER NOT NULL DEFAULT 0;

ALTER TABLE ORDEM_SERVICO
    ADD COLUMN CRIADO_EM TIMESTAMP,
DROP COLUMN TERMINADO_EM;

ALTER TABLE ORDEM_SERVICO
    RENAME COLUMN MECANICO_FINAL_ID TO MECANICO_RESPONSAVEL_ID;

ALTER TABLE EXECUCAO_SERVICO
    RENAME COLUMN ATENDENTE_ID TO ATENDENTE_APROVACAO_ID;