-- ROLE
CREATE TABLE ROLE (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

-- CARGO
CREATE TABLE CARGO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

-- FUNCIONARIO
CREATE TABLE FUNCIONARIO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    CARGO_ID BIGINT,
    CONSTRAINT FK_FUNCIONARIO_CARGO
        FOREIGN KEY (CARGO_ID) REFERENCES CARGO(ID)
);

-- TABELA DE RELACIONAMENTO (ManyToMany)
CREATE TABLE CARGO_ROLE (
    CARGO_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,

    PRIMARY KEY (CARGO_ID, ROLE_ID),

    CONSTRAINT FK_CARGO_ROLE_CARGO
        FOREIGN KEY (CARGO_ID) REFERENCES CARGO(ID),

    CONSTRAINT FK_CARGO_ROLE_ROLE
        FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);