-- AUTH

CREATE TABLE ROLE (
    ID   UUID        NOT NULL,
    NOME VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);

CREATE TABLE CARGO (
    ID   SERIAL      PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL
);

CREATE TABLE USERS (
    ID                UUID         NOT NULL,
    USER_NAME         VARCHAR(255) NOT NULL,
    EMAIL             VARCHAR(255) NOT NULL,
    CREDENTIAL        VARCHAR(255) NOT NULL,
    ATIVO             BOOLEAN      NOT NULL,
    CRIACAO_DATE      TIMESTAMP    NOT NULL,
    ULTIMO_LOGIN_DATE TIMESTAMP,
    CONSTRAINT PK_USERS       PRIMARY KEY (ID),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE USER_ROLES (
    USER_ID UUID NOT NULL,
    ROLE_ID UUID NOT NULL,
    CONSTRAINT PK_USER_ROLES      PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

CREATE TABLE CARGO_ROLE (
    CARGO_ID BIGINT NOT NULL,
    ROLE_ID  UUID   NOT NULL,
    CONSTRAINT PK_CARGO_ROLE       PRIMARY KEY (CARGO_ID, ROLE_ID),
    CONSTRAINT FK_CARGO_ROLE_CARGO FOREIGN KEY (CARGO_ID) REFERENCES CARGO(ID),
    CONSTRAINT FK_CARGO_ROLE_ROLE  FOREIGN KEY (ROLE_ID)  REFERENCES ROLE(ID)
);

CREATE TABLE FUNCIONARIO (
    ID       BIGSERIAL    PRIMARY KEY,
    NOME     VARCHAR(100) NOT NULL,
    CARGO_ID BIGINT       NOT NULL,
    USER_ID  UUID         NOT NULL,
    CONSTRAINT FK_FUNCIONARIO_CARGO FOREIGN KEY (CARGO_ID) REFERENCES CARGO(ID),
    CONSTRAINT FK_FUNCIONARIO_USER  FOREIGN KEY (USER_ID)  REFERENCES USERS(ID)
);

-- DOMAIN

CREATE TABLE PROPRIETARIO (
    ID             BIGSERIAL    PRIMARY KEY,
    NOME           VARCHAR(255) NOT NULL,
    EMAIL          VARCHAR(255) NOT NULL,
    DOCUMENTO      VARCHAR(14)  NOT NULL UNIQUE,
    NUMERO_CELULAR VARCHAR(11)  NOT NULL,
    RUA            VARCHAR(255),
    CEP            VARCHAR(8),
    NUMERO_CASA    VARCHAR(20),
    ATIVO          BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE VEICULO (
    ID              BIGSERIAL    PRIMARY KEY,
    PROPRIETARIO_ID BIGINT       NOT NULL,
    PLACA           VARCHAR(7)   NOT NULL UNIQUE,
    MARCA           VARCHAR(100) NOT NULL,
    MODELO          VARCHAR(100) NOT NULL,
    ANO             INTEGER      NOT NULL,
    COR             VARCHAR(50)  NOT NULL,
    ATIVO           BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT FK_VEICULO_PROPRIETARIO FOREIGN KEY (PROPRIETARIO_ID) REFERENCES PROPRIETARIO(ID)
);

CREATE TABLE SERVICO (
    ID        BIGSERIAL    PRIMARY KEY,
    NOME      VARCHAR(150) NOT NULL,
    DESCRICAO TEXT,
    ATIVO     BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE PECA (
    ID        BIGSERIAL     PRIMARY KEY,
    NOME      VARCHAR(150)  NOT NULL,
    DESCRICAO TEXT,
    VALOR     NUMERIC(10,2) NOT NULL,
    ATIVO     BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TABLE PECA_ESTOQUE (
    PECA_ID               BIGINT  PRIMARY KEY,
    QUANTIDADE_ARMAZENADA INTEGER NOT NULL,
    QUANTIDADE_DISPONIVEL INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT FK_PECA_ESTOQUE FOREIGN KEY (PECA_ID) REFERENCES PECA(ID)
);

CREATE TABLE ORDEM_SERVICO (
    ID                      BIGSERIAL     PRIMARY KEY,
    PROPRIETARIO_ID         BIGINT        NOT NULL,
    VEICULO_ID              BIGINT        NOT NULL,
    RECLAMACAO_PROPRIETARIO TEXT,
    STATUS                  VARCHAR(30),
    INICIADO_EM             TIMESTAMP,
    FINALIZADO_EM           TIMESTAMP,
    ENTREGUE_EM             TIMESTAMP,
    ATUALIZADO_EM           TIMESTAMP,
    CRIADO_EM               TIMESTAMP,
    ATENDENTE_INICIO_ID     BIGINT        NOT NULL,
    MECANICO_RESPONSAVEL_ID BIGINT,
    VALOR_TOTAL             NUMERIC(10,2)
);

CREATE TABLE EXECUCAO_SERVICO (
    ID                      BIGSERIAL     PRIMARY KEY,
    STATUS_SERVICO          VARCHAR(30),
    ATENDENTE_APROVACAO_ID  BIGINT,
    SERVICO_ID              BIGINT        NOT NULL,
    OS_ID                   BIGINT        NOT NULL,
    INICIADO_EM             TIMESTAMP,
    TERMINADO_EM            TIMESTAMP,
    MECANICO_RESPONSAVEL_ID BIGINT,
    VALOR_MAO_DE_OBRA       NUMERIC(10,2),
    ATUALIZADO_EM           TIMESTAMP,
    CONSTRAINT FK_EXECUCAO_SERVICO_SERVICO FOREIGN KEY (SERVICO_ID) REFERENCES SERVICO(ID),
    CONSTRAINT FK_EXECUCAO_SERVICO_OS      FOREIGN KEY (OS_ID)      REFERENCES ORDEM_SERVICO(ID)
);

CREATE TABLE PECA_ALOCADA (
    ID                  BIGSERIAL     PRIMARY KEY,
    EXECUCAO_SERVICO_ID BIGINT        NOT NULL,
    PECA_ID             BIGINT        NOT NULL,
    STATUS              VARCHAR(30)   NOT NULL,
    ATUALIZADO_EM       TIMESTAMP,
    QTD_SOLICITADA      INTEGER       NOT NULL,
    QTD_RESERVADA       INTEGER       NOT NULL DEFAULT 0,
    QTD_ENCOMENDADA     INTEGER       NOT NULL DEFAULT 0,
    VALOR_UNITARIO      NUMERIC(10,2) NOT NULL DEFAULT 0,
    QTD_INSTALADA       INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT FK_PECA_ALOCADA_EXECUCAO FOREIGN KEY (EXECUCAO_SERVICO_ID) REFERENCES EXECUCAO_SERVICO(ID),
    CONSTRAINT FK_PECA_ALOCADA_PECA     FOREIGN KEY (PECA_ID)              REFERENCES PECA(ID),
    CONSTRAINT UK_PECA_ALOCADA          UNIQUE (EXECUCAO_SERVICO_ID, PECA_ID)
);
