CREATE TABLE PROPRIETARIO (
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DOCUMENTO VARCHAR(14) NOT NULL UNIQUE,
    NUMERO_CELULAR VARCHAR(11) NOT NULL,
    RUA VARCHAR(255),
    CEP VARCHAR(8),
    NUMERO_CASA VARCHAR(20)
);

CREATE TABLE VEICULO (
    ID BIGSERIAL PRIMARY KEY,
    PROPRIETARIO_ID BIGINT NOT NULL,
    PLACA VARCHAR(7) NOT NULL UNIQUE,
    MARCA VARCHAR(100) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    ANO INTEGER NOT NULL,
    COR VARCHAR(50) NOT NULL,
    CONSTRAINT FK_VEICULO_PROPRIETARIO FOREIGN KEY (PROPRIETARIO_ID) REFERENCES PROPRIETARIO(ID)
);