-- PROPRIETÁRIOS
INSERT INTO PROPRIETARIO (NOME, EMAIL, DOCUMENTO, NUMERO_CELULAR, RUA, CEP, NUMERO_CASA, ATIVO)
VALUES ('Carlos Silva', 'carlos@email.com', '46924388000', '11999990001', 'Rua das Flores', '01234567', '100', TRUE);

INSERT INTO PROPRIETARIO (NOME, EMAIL, DOCUMENTO, NUMERO_CELULAR, RUA, CEP, NUMERO_CASA, ATIVO)
VALUES ('Ana Oliveira', 'ana@email.com', '57126491018', '11999990002', 'Av Paulista', '01310100', '1500', TRUE);

INSERT INTO PROPRIETARIO (NOME, EMAIL, DOCUMENTO, NUMERO_CELULAR, RUA, CEP, NUMERO_CASA, ATIVO)
VALUES ('Auto Center Ltda', 'contato@autocenter.com', '91555965091', '11999990003', 'Rua da Industria', '09876543', '250', TRUE);

-- VEÍCULOS
-- Carlos (id=1)
INSERT INTO VEICULO (PROPRIETARIO_ID, PLACA, MARCA, MODELO, ANO, COR, ATIVO)
VALUES (1, 'ABC1D23', 'Fiat', 'Uno', 2020, 'Prata', TRUE);

INSERT INTO VEICULO (PROPRIETARIO_ID, PLACA, MARCA, MODELO, ANO, COR, ATIVO)
VALUES (1, 'XYZ4E56', 'Volkswagen', 'Gol', 2019, 'Branco', TRUE);

-- Ana (id=2)
INSERT INTO VEICULO (PROPRIETARIO_ID, PLACA, MARCA, MODELO, ANO, COR, ATIVO)
VALUES (2, 'DEF7G89', 'Toyota', 'Corolla', 2023, 'Preto', TRUE);

-- Auto Center (id=3)
INSERT INTO VEICULO (PROPRIETARIO_ID, PLACA, MARCA, MODELO, ANO, COR, ATIVO)
VALUES (3, 'GHI1J23', 'Chevrolet', 'Onix', 2022, 'Vermelho', TRUE);

INSERT INTO VEICULO (PROPRIETARIO_ID, PLACA, MARCA, MODELO, ANO, COR, ATIVO)
VALUES (3, 'JKL4M56', 'Hyundai', 'HB20', 2021, 'Azul', FALSE);

INSERT INTO VEICULO (PROPRIETARIO_ID, PLACA, MARCA, MODELO, ANO, COR, ATIVO)
VALUES (3, 'MNO7P89', 'Honda', 'Civic', 2024, 'Cinza', TRUE);