CREATE TABLE SERVICO (
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO TEXT
);

CREATE TABLE PECA (
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO TEXT,
    VALOR NUMERIC(10,2) NOT NULL
);

CREATE TABLE PECA_ESTOQUE (
    PECA_ID BIGINT PRIMARY KEY,
    QUANTIDADE_ARMAZENADA INTEGER NOT NULL,
    CONSTRAINT FK_PECA_ESTOQUE
        FOREIGN KEY (PECA_ID) REFERENCES PECA(ID)
);

CREATE TABLE ORDEM_SERVICO (
    ID BIGSERIAL PRIMARY KEY,
    PROPRIETARIO_ID BIGINT,
    VEICULO_ID BIGINT,
    RECLAMACAO_CLIENTE TEXT,
    STATUS VARCHAR(30),

    INICIADO_EM TIMESTAMP,
    FINALIZADO_EM TIMESTAMP,
    ENTREGUE_EM TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP,

    ATENDENTE_INICIO_ID BIGINT,
    TERMINADO_EM TIMESTAMP,
    MECANICO_FINAL_ID BIGINT,

    VALOR_TOTAL NUMERIC(10,2)
);

CREATE TABLE SERVICO_OS (
    ID BIGSERIAL PRIMARY KEY,
    STATUS_SERVICO VARCHAR(30),
    ATENDENTE_ID BIGINT,

    SERVICO_ID BIGINT NOT NULL,
    OS_ID BIGINT NOT NULL,

    INICIADO_EM TIMESTAMP,
    TERMINADO_EM TIMESTAMP,

    MECANICO_RESPONSAVEL_ID BIGINT,

    VALOR_MAO_DE_OBRA NUMERIC(10,2),
    ATUALIZADO_EM TIMESTAMP,

    CONSTRAINT FK_SERVICO_OS_SERVICO
        FOREIGN KEY (SERVICO_ID) REFERENCES SERVICO(ID),

    CONSTRAINT FK_SERVICO_OS_OS
        FOREIGN KEY (OS_ID) REFERENCES ORDEM_SERVICO(ID)
);

CREATE TABLE PECA_ALOCADA (
    ID BIGSERIAL PRIMARY KEY,
    SERVICO_OS_ID BIGINT NOT NULL,
    PECA_ID BIGINT NOT NULL,
    QUANTIDADE_ALOCADA INTEGER NOT NULL,

    CONSTRAINT FK_PECA_ALOCADA_SERVICO
        FOREIGN KEY (SERVICO_OS_ID) REFERENCES SERVICO_OS(ID),

    CONSTRAINT FK_PECA_ALOCADA_PECA
        FOREIGN KEY (PECA_ID) REFERENCES PECA(ID)
);