CREATE TABLE SERVICO (
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO TEXT
);

CREATE TABLE PECA (
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO TEXT,
    VALOR NUMERIC(10,2) NOT NULL
);

CREATE TABLE PECA_ESTOQUE (
    PECA_ID BIGINT PRIMARY KEY,
    QUANTIDADE_ARMAZENADA INTEGER NOT NULL,
    CONSTRAINT FK_PECA_ESTOQUE
        FOREIGN KEY (PECA_ID) REFERENCES PECA(ID)
);

CREATE TABLE ORDEM_SERVICO (
    ID BIGSERIAL PRIMARY KEY,
    PROPRIETARIO_ID BIGINT NOT NULL,
    VEICULO_ID BIGINT NOT NULL,
    RECLAMACAO_CLIENTE TEXT,
    STATUS VARCHAR(30),

    INICIADO_EM TIMESTAMP,
    FINALIZADO_EM TIMESTAMP,
    ENTREGUE_EM TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP,

    ATENDENTE_INICIO_ID BIGINT NOT NULL,
    TERMINADO_EM TIMESTAMP,
    MECANICO_FINAL_ID BIGINT,

    VALOR_TOTAL NUMERIC(10,2)
);

CREATE TABLE EXECUCAO_SERVICO (
    ID BIGSERIAL PRIMARY KEY,
    STATUS_SERVICO VARCHAR(30),
    ATENDENTE_ID BIGINT,

    SERVICO_ID BIGINT NOT NULL,
    OS_ID BIGINT NOT NULL,

    INICIADO_EM TIMESTAMP,
    TERMINADO_EM TIMESTAMP,

    MECANICO_RESPONSAVEL_ID BIGINT,

    VALOR_MAO_DE_OBRA NUMERIC(10,2),
    ATUALIZADO_EM TIMESTAMP,

    CONSTRAINT FK_EXECUCAO_SERVICO_SERVICO
        FOREIGN KEY (SERVICO_ID) REFERENCES SERVICO(ID),

    CONSTRAINT FK_EXECUCAO_SERVICO_OS
        FOREIGN KEY (OS_ID) REFERENCES ORDEM_SERVICO(ID)
);

CREATE TABLE PECA_ALOCADA (
    ID BIGSERIAL PRIMARY KEY,
    EXECUCAO_SERVICO_ID BIGINT NOT NULL,
    PECA_ID BIGINT NOT NULL,

    STATUS VARCHAR(30) NOT NULL,
    ATUALIZADO_EM TIMESTAMP,

    QTD_SOLICITADA INTEGER NOT NULL,
    QTD_RESERVADA INTEGER NOT NULL DEFAULT 0,
    QTD_ENCOMENDADA INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT FK_PECA_ALOCADA_SERVICO
        FOREIGN KEY (EXECUCAO_SERVICO_ID) REFERENCES EXECUCAO_SERVICO(ID),

    CONSTRAINT FK_PECA_ALOCADA_PECA
        FOREIGN KEY (PECA_ID) REFERENCES PECA(ID),

    CONSTRAINT UK_PECA_ALOCADA UNIQUE (EXECUCAO_SERVICO_ID, PECA_ID)
);